### ISSUE TITLE
CPU Frequency Value Incorrect in TCC

### ISSUE THREAD

**Issue by bwyyoung** [tuxedocomputers/tuxedo-corefix-clevo-nh5xax#1]
After applying the fix, the value reported in TCC for CPU frequency is incorrect when compared to CoreCtrl.

My laptop is the Aftershock Forge 15R (NH5xAx) running POP! OS with an AMD 3950X CPU.

Please see this screenshot:
![Screenshot from 2021-02-06 23-51-11](https://user-images.githubusercontent.com/1365439/107123069-7fb83200-68d6-11eb-9c4f-35c756a2a3ea.png)

**Comment by Matombo** [comment]
Hello,

can you please check what frequency lscpu reports?

In tcc is the 2.2 Ghz fixed or does it still change (just to wrong values)?

**Comment by bwyyoung** [comment]
Hi sorry, I read your message late.

It seems that TCC only moves in fixed increments when it comes to CPU frequency display, and the UI itself is not accurate. Will test again another day. Thank you.
