### ISSUE TITLE
POP! OS 20.10 (Groovy)

### ISSUE THREAD

**Issue by bwyyoung** [tuxedocomputers/tuxedo-corefix-clevo-nh5xax#2]
I tested corefix on POP! OS 20.10.

However, it does not seem to work.

It previously worked on 20.04, but not 20.10.

Now, there is no CPU frequency display.
This is with TCC v1.0.13

I tried reinstalling (./install_ubuntu.sh) but it does not seem to work, even after rebooting the laptop.

![snapshot](https://user-images.githubusercontent.com/1365439/117671468-67a8c500-b1db-11eb-89e6-2e890affafb4.png)

**Comment by Matombo** [comment]
I did not test POP! OS, but I guess the source of the bug is the same:

A regression bug in the Ubuntu kernel broke corefix. The fix is already commited and will most likely land in Ubuntus 5.8.0-56 kernel: https://kernel.ubuntu.com/git/ubuntu/ubuntu-focal.git/commit/?h=hwe-5.8&id=7c54d847d3bd237e7e8a217f1aa9994b64d9d282

I guess it will soon after also land in POP! OS.

**Comment by bwyyoung** [comment]
Hi @Matombo. I saw your reply and was speaking with Can from support.

Thanks for helping me on this. However, the link you provided was for Ubuntu-Focal (20.04), and not Ubuntu Groovy (20.10). 
Does Groovy have the same issue? Or does it remain unresolved in 20.10?
I ask because my version of POP! OS is running on Groovy.

**Comment by Matombo** [comment]
If a patch is applicable for multiple supported ubuntu version it usually gets applied to all of them, so yes it's also on the groovy 5.8.0 kernel: https://kernel.ubuntu.com/git/ubuntu/ubuntu-groovy.git/commit/?id=7c54d847d3bd237e7e8a217f1aa9994b64d9d282

**Comment by bwyyoung** [comment]
Hi @Matombo.
I just did a dist-upgrade, and my updated kernel version is
5.11.0-7620-generic
on Groovy.

Now, it seems that TCC works. I haven't applied the Corefix patch,
but it seems to work on the latest dist-upgrade kernel.

```
cat /etc/os-release
NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os


```

**Comment by Matombo** [comment]
You can check if everything works normal with `ls -la /sys/devices/system/cpu/cpufreq/` if you see policy 0-31 then all cores are correctly recognized, if you only see 0-23 then corefix is not installed or not working for some reason.

If you never uninstalled corefix, it's still active. You don't need to apply it to each kernel sepperatly. It installs a hook script that adds the required fixed ACPI table to every initramfs.img, that is created for your system, automatically.

**Comment by bwyyoung** [comment]
Thank you @Matombo. 

I hope TCC will be updated for 21.04 in future.

Take care.
