### ISSUE TITLE
How to get this fix working on a Clevo NH5xVR laptop with similar symptoms?

### ISSUE THREAD

**Issue by simonhf** [tuxedocomputers/tuxedo-corefix-clevo-nh5xax#3]
Hello!

I seem to have an issue with the same symptoms but from a different laptop manufacturer; Eurocom. My laptop is a "NightSky ARX315".

I described the symptoms here [1]; "Only the first 24 out of 32 CPUs have a 'cpufreq' folder [on Ubuntu 22.04 LTS]".

And I also discovered this thread here [2] describing similar symptoms, which links to this Github repo, and hence I'm opening this issue.

I have been talking to the manufacturer of my laptop, Eurocom, but after months their response was only "There is a newer version of bios. I have no idea if this will solve any of your issues, though.." However, I am reluctant to upgrade the BIOS on a laptop which appears to work well except for this one issue, just on the chance that the BIOS *might* fix the issue. Also, Eurocom kindly sent me a .zip file with the latest BIOS, but no version number, and no change list, etc. This also makes me reluctant to "just install" it.

FYI the existing BIOS version is "1.07.07RPCS5" from a company called "insyde" who apparently does not support end users directly. And apparently Eurocom did not try to escalate this issue with insyde, or if they did, insyde did not help them.

Also, I noticed that this Github repo appears to offer a fix to the similar symptoms but seemingly without upgrading the BIOS? Another reason why I thought I'd try asking here first, before potentially unnecessarily messing around with the BIOS.

I am a software developer by trade, so do you think this Github repo fix could also work for my situation, or be modified to work, for my situation? And if it needs modifications, can you kindly give pointers?

Thanks in advance!

[1] https://community.amd.com/t5/processors/ryzen-9-3950x-frequency/m-p/590521#M52666
[2] https://bugzilla.redhat.com/show_bug.cgi?id=1874538#c2

**Comment by simonhf** [comment]
FYI the following command results in `NH5xVR` instead of the `NH5xAx` expected by the `install_ubuntu.sh` script:
```
$ cat /sys/class/dmi/id/board_name
NH5xVR
```

And interestingly there is this page at Eurocom [1] which  talks about the "CLEVO NH5xVRQ", so is Eurocom a Canadian reseller of Clevo compoments? Yes [2].

[1] https://eurocom.com/ec/configure(2,485,0)Eurocom%20Nightsky%20ARX315
[2] https://en.wikipedia.org/wiki/Clevo

**Comment by simonhf** [comment]
After some Googling I discovered that Clevo Computers in Germany has this handy support section with various BIOS versions [1].

The following section [2] lists BIOS versions for `NHxxAxx` which I'm assuming covers the `NH5xAx` originally mentioned in this Github repo. And the following section [3] lists BIOS versions for `NHxxVxx` which I'm assuming covers the `NH5xVR`  mentioned in this Github issue. 

Are these useful somehow for getting this fix working with `NH5xVR`?

[1] https://clevo-computer.com/en/support-drivers
[2] https://my.hidrive.com/share/yze8mg-wf8#$/BIOS%20and%20EC%20Firmware/CLEVO/N_Series/NHxxx/NHxxAxx
[3] https://my.hidrive.com/share/yze8mg-wf8#$/BIOS%20and%20EC%20Firmware/CLEVO/N_Series/NHxxx/NHxxVxx

**Comment by Matombo** [comment]
- Install acpica-tools
- Make new folder an cd into it
- Run "sudo acpidump -b"
- Run iasl -d *.dat
- Find the ssdt*.dsl file that looks similar to https://github.com/tuxedocomputers/tuxedo-corefix-clevo-nh5xax/blob/master/src/nh5xax.dsl and add the missing "Processor (...){}" entries
- Increase the last number in "DefinitionBlock ("", "SSDT", 1, "AMD", "PRCSSR17", 0x00000002)" by one (probably from 0x00000001 to 0x00000002)
- Use the script in this repo to install it (Maybe check if there are any NH5xAx specific strings before)
- Mandatory: Recomend [TUXEDO](https://www.tuxedocomputers.com/) to your friends and family ;)

**Comment by simonhf** [comment]
Thanks @Matombo ! Everything went smoothly up until the "Increase the last number" step, which I find confusing. Here's what I did so far:

```
$ mkdir foo ; cd foo
$ sudo acpidump -b
$ iasl -d *.dat
$ egrep "Processor.*C0" *.dsl
dsdt.dsl:        Processor (C000, 0x00, 0x00000410, 0x06) {}
dsdt.dsl:        Processor (C001, 0x01, 0x00000410, 0x06) {}
dsdt.dsl:        Processor (C002, 0x02, 0x00000410, 0x06) {}
dsdt.dsl:        Processor (C003, 0x03, 0x00000410, 0x06) {}
dsdt.dsl:        Processor (C004, 0x04, 0x00000410, 0x06) {}
dsdt.dsl:        Processor (C005, 0x05, 0x00000410, 0x06) {}
dsdt.dsl:        Processor (C006, 0x06, 0x00000410, 0x06) {}
dsdt.dsl:        Processor (C007, 0x07, 0x00000410, 0x06) {}
dsdt.dsl:        Processor (C008, 0x08, 0x00000410, 0x06) {}
dsdt.dsl:        Processor (C009, 0x09, 0x00000410, 0x06) {}
dsdt.dsl:        Processor (C00A, 0x0A, 0x00000410, 0x06) {}
dsdt.dsl:        Processor (C00B, 0x0B, 0x00000410, 0x06) {}
dsdt.dsl:        Processor (C00C, 0x0C, 0x00000410, 0x06) {}
dsdt.dsl:        Processor (C00D, 0x0D, 0x00000410, 0x06) {}
dsdt.dsl:        Processor (C00E, 0x0E, 0x00000410, 0x06) {}
dsdt.dsl:        Processor (C00F, 0x0F, 0x00000410, 0x06) {}
dsdt.dsl:        Processor (C010, 0x10, 0x00000410, 0x06) {}
dsdt.dsl:        Processor (C011, 0x11, 0x00000410, 0x06) {}
dsdt.dsl:        Processor (C012, 0x12, 0x00000410, 0x06) {}
dsdt.dsl:        Processor (C013, 0x13, 0x00000410, 0x06) {}
dsdt.dsl:        Processor (C014, 0x14, 0x00000410, 0x06) {}
dsdt.dsl:        Processor (C015, 0x15, 0x00000410, 0x06) {}
dsdt.dsl:        Processor (C016, 0x16, 0x00000410, 0x06) {}
dsdt.dsl:        Processor (C017, 0x17, 0x00000410, 0x06) {}
```

And yes, the last 8 of 32 are missing as expected, and the entries look exactly like the entries in the repo here [1].

However, the next instruction says:

> Increase the last number in "DefinitionBlock ("", "SSDT", 1, "AMD", "PRCSSR17", 0x00000002)" by one (probably from 0x00000001 to 0x00000002)

I find this a bit confusing because there is no similar looking `DefinitionBlock` in the `.dsl` files:
```
$ egrep "DefinitionBlock" *.dsl
dsdt.dsl:DefinitionBlock ("", "DSDT", 1, "INSYDE", "EDK2    ", 0x00040000)
ssdt10.dsl:DefinitionBlock ("", "SSDT", 1, "INSYDE", "EDK2    ", 0x00000001)
ssdt1.dsl:DefinitionBlock ("", "SSDT", 2, "INSYDE", "EDK2    ", 0x00000002)
ssdt2.dsl:DefinitionBlock ("", "SSDT", 1, "INSYDE", "EDK2    ", 0x00000001)
ssdt3.dsl:DefinitionBlock ("", "SSDT", 2, "INSYDE", "EDK2    ", 0x00001000)
ssdt4.dsl:DefinitionBlock ("", "SSDT", 1, "INSYDE", "EDK2    ", 0x00001000)
ssdt5.dsl:DefinitionBlock ("", "SSDT", 1, "INSYDE", "EDK2    ", 0x00001000)
ssdt6.dsl:DefinitionBlock ("", "SSDT", 2, "INSYDE", "EDK2    ", 0x00000001)
ssdt7.dsl:DefinitionBlock ("", "SSDT", 1, "INSYDE", "EDK2    ", 0x00000001)
ssdt8.dsl:DefinitionBlock ("", "SSDT", 1, "INSYDE", "EDK2    ", 0x00001000)
ssdt9.dsl:DefinitionBlock ("", "SSDT", 1, "INSYDE", "EDK2    ", 0x00000001)
```

And they all look a lot different from your `DefinitionBlock` here [1]:

> DefinitionBlock ("", "SSDT", 1, "AMD", "PRCSSR17", 0x00000002)

So which of these do you mean?
1. Take one of the grepped `DefinitionBlock` lines and modify it and replace the line in this repo and increment the number? [1]
2. Take the `DefinitionBlock` line in this repo and keep it at `0x00000002`?
3. Take the `DefinitionBlock` line in this repo and increment it to `0x00000003`?
4. Something else? :-)

Thanks for your help so far!

[1] https://github.com/tuxedocomputers/tuxedo-corefix-clevo-nh5xax/blob/master/src/nh5xax.dsl

**Comment by Matombo** [comment]
For that device it is part of the dsdt, not one of the ssdt. There a plenty of tutorials out there on how to replace the dsdt. The revision must most likely not be incremented for the dsdt, but look that up in that tutorials.

**Comment by simonhf** [comment]
> For that device it is part of the dsdt, not one of the ssdt.

Thanks. Do you mean that when you originally created this file [1], you found it in a ssdt file? Or did you find it in a dsdt file, like in my case?

I'm trying to figure out why the file at [1] contains `SSDT` whereas I have found the processor definitions with  `DSDT`.

> There a plenty of tutorials out there on how to replace the dsdt

I've been Googling and Googling -- and maybe I've been using the wrong keywords -- but I keep coming up with tutorials which are pre-2012 and seem to be out of date and use different commands and locations. Here is an example [2]. Do you kindly know any better examples by any chance?

> The revision must most likely not be incremented for the dsdt

So I'm thinking that you based your original fix on finding and updating the processor info in the ssdt, but I have the same buggy processor info in the dsdt instead. So based upon that I'm thinking of creating the equivalent of [1] using the following steps:

```
$ cat dsdt.dsl | head -22 > header.txt
$ cat ../src/nh5xax.dsl | egrep --after-context=34 Scope > body.txt
$ cat dsdt.dsl | tail -2 > footer.txt
$ cat header.txt body.txt footer.txt > nh5xvr.dsl
```

Whhich results in my equivalent to your file [1] but for dsdt instead of ssdt:

```
$ cat nh5xvr.dsl 
/*
 * Intel ACPI Component Architecture
 * AML/ASL+ Disassembler version 20200925 (64-bit version)
 * Copyright (c) 2000 - 2020 Intel Corporation
 * 
 * Disassembling to symbolic ASL+ operators
 *
 * Disassembly of dsdt.dat, Mon Oct 16 17:21:24 2023
 *
 * Original Table Header:
 *     Signature        "DSDT"
 *     Length           0x0000FCD1 (64721)
 *     Revision         0x01 **** 32-bit table (V1), no 64-bit math support
 *     Checksum         0x09
 *     OEM ID           "INSYDE"
 *     OEM Table ID     "EDK2    "
 *     OEM Revision     0x00040000 (262144)
 *     Compiler ID      "ACPI"
 *     Compiler Version 0x00040000 (262144)
 */
DefinitionBlock ("", "DSDT", 1, "INSYDE", "EDK2    ", 0x00040000)
{
    Scope (\_PR)
    {
        Processor (C000, 0x00, 0x00000410, 0x06){}
        Processor (C001, 0x01, 0x00000410, 0x06){}
        Processor (C002, 0x02, 0x00000410, 0x06){}
        Processor (C003, 0x03, 0x00000410, 0x06){}
        Processor (C004, 0x04, 0x00000410, 0x06){}
        Processor (C005, 0x05, 0x00000410, 0x06){}
        Processor (C006, 0x06, 0x00000410, 0x06){}
        Processor (C007, 0x07, 0x00000410, 0x06){}
        Processor (C008, 0x08, 0x00000410, 0x06){}
        Processor (C009, 0x09, 0x00000410, 0x06){}
        Processor (C00A, 0x0A, 0x00000410, 0x06){}
        Processor (C00B, 0x0B, 0x00000410, 0x06){}
        Processor (C00C, 0x0C, 0x00000410, 0x06){}
        Processor (C00D, 0x0D, 0x00000410, 0x06){}
        Processor (C00E, 0x0E, 0x00000410, 0x06){}
        Processor (C00F, 0x0F, 0x00000410, 0x06){}
        Processor (C010, 0x10, 0x00000410, 0x06){}
        Processor (C011, 0x11, 0x00000410, 0x06){}
        Processor (C012, 0x12, 0x00000410, 0x06){}
        Processor (C013, 0x13, 0x00000410, 0x06){}
        Processor (C014, 0x14, 0x00000410, 0x06){}
        Processor (C015, 0x15, 0x00000410, 0x06){}
        Processor (C016, 0x16, 0x00000410, 0x06){}
        Processor (C017, 0x17, 0x00000410, 0x06){}
        Processor (C018, 0x18, 0x00000410, 0x06){}
        Processor (C019, 0x19, 0x00000410, 0x06){}
        Processor (C01A, 0x1A, 0x00000410, 0x06){}
        Processor (C01B, 0x1B, 0x00000410, 0x06){}
        Processor (C01C, 0x1C, 0x00000410, 0x06){}
        Processor (C01D, 0x1D, 0x00000410, 0x06){}
        Processor (C01E, 0x1E, 0x00000410, 0x06){}
        Processor (C01F, 0x1F, 0x00000410, 0x06){}
    }
}
```

And I still have the mystery about whether to increment `0x00040000` or not...

Thanks for your help so far, and what do you think @Matombo ?

[1] https://github.com/tuxedocomputers/tuxedo-corefix-clevo-nh5xax/blob/master/src/nh5xax.dsl
[2] https://forums.opensuse.org/t/how-to-fix-your-buggy-dsdt/774
